name: Politik Scraper

on:
  schedule:
    # Runs every day at 8 PM UTC
    # Adjust the cron schedule if your desired 8 PM is in a different timezone.
    # For example, for 8 PM CET (UTC+1), you might use '0 19 * * *'
    # For 8 PM CEST (UTC+2), you might use '0 18 * * *'
    - cron: '0 20 * * *' 
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape_and_send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3 version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper script
      run: python src/main.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
